# -*- coding: utf-8 -*-
"""Data source for _apply.mjs: rewritten correct+wrongs (120-165 chars),
coherent near-miss protocols, unique suffixes, correct kept in the interior
of the length distribution (skew=0) on puericultura items.

Targets per question: correct ~139-143; two shorter wrongs ~126-133;
two longer wrongs ~146-152. Guarantees min < len(correct) < max."""

# ---- part7 (ALL items, keyed by n) ----
P7 = {
1: ("aplicar pentavalente (DTP+Hib+hepatite B), poliomielite inativada (VIP), pneumocócica 10-valente e rotavírus conforme o calendário do PNI",
 ["aplicar apenas pentavalente e VIP hoje, adiando a pneumocócica e o rotavírus para um retorno na próxima semana",
  "aplicar pentavalente, VIP e pneumocócica hoje, deixando somente o rotavírus para a consulta do terceiro mês",
  "aplicar pentavalente, poliomielite oral (VOP), pneumocócica 10-valente e rotavírus, iniciando a proteção contra a pólio já com a vacina oral em gotas",
  "aplicar pentavalente, VIP, pneumocócica 10-valente, rotavírus e também a meningocócica C, antecipando para hoje a dose que seria feita aos 3 meses"]),
2: ("a meningocócica C é feita aos 3 e 5 meses, com um reforço aos 12 meses, e a meningocócica ACWY é oferecida como reforço na adolescência",
 ["a meningocócica C é feita em dose única aos 3 meses, sem reforço posterior, e a ACWY entra somente em surtos",
  "a meningocócica C é feita só aos 5 meses, sem qualquer reforço, e a ACWY nunca entra no calendário de rotina",
  "a meningocócica ACWY é aplicada aos 3 e 5 meses e a meningocócica C fica reservada apenas como reforço único durante a fase adulta jovem do paciente",
  "a meningocócica C é feita aos 3 e 5 meses, mas o reforço só ocorre aos 6 meses, ficando a ACWY indicada já a partir dos 12 meses de idade da criança"]),
3: ("aplicar a febre amarela aos 9 meses e a tríplice viral aos 12 meses; quando não forem no mesmo dia, respeitar intervalo mínimo de 30 dias",
 ["contraindicar a febre amarela nesta idade e aplicar apenas a tríplice viral aos 12 meses, evitando o vírus vivo",
  "adiar a febre amarela para depois dos 5 anos e aplicar somente a tríplice viral no calendário do primeiro ano",
  "aplicar febre amarela e tríplice viral no mesmo dia é proibido; deixar sempre um intervalo mínimo de 7 dias entre as duas vacinas de vírus vivo",
  "aplicar as duas vacinas no mesmo dia é obrigatório; caso contrário, exigir intervalo mínimo de 15 dias entre a febre amarela e a tríplice viral"]),
4: ("aplicar dTpa na gestante a partir de 20 semanas, a cada gestação, e adotar a estratégia cocoon vacinando os contactantes próximos do bebê",
 ["não vacinar a gestante e apenas antecipar o esquema do bebê, iniciando a pentavalente já na primeira semana",
  "aplicar dTpa na gestante somente no puerpério, dispensando por completo a vacinação dos contactantes do bebê",
  "aplicar a pentavalente na gestante por ter componente pertussis e orientar que os contactantes atualizem apenas a vacina dupla adulto (dT) no posto",
  "aplicar dTpa na gestante a partir de 20 semanas, mas reservar a estratégia cocoon apenas para famílias com um caso já confirmado de coqueluche"]),
5: ("a vacina herpes-zóster é destinada a adultos e idosos, não a crianças; a prevenção da varicela na infância é feita com tetra viral e varicela",
 ["não existe qualquer vacinação contra a varicela no calendário infantil brasileiro, restando só a herpes-zóster",
  "a vacina herpes-zóster deve ser aplicada aos 12 meses para prevenir a varicela precoce nessa faixa etária",
  "antecipar as vacinas herpes-zóster e varicela juntas aos 10 meses de idade, garantindo uma proteção mais precoce contra a catapora e o cobreiro",
  "a vacina herpes-zóster substitui a vacina varicela em toda criança acima de 9 meses, dispensando a aplicação da tetra viral no segundo ano de vida"]),
6: ("manter o acompanhamento clínico de rotina, pois a curva estável no mesmo canal com exame neurológico normal não exige qualquer neuroimagem",
 ["interromper o registro do perímetro cefálico após os 3 meses, achando que a medida perderia o valor clínico",
  "encaminhar à neurocirurgia apenas pela percepção materna de que a cabeça do bebê estaria um pouco grande",
  "solicitar tomografia de crânio de rotina sempre que a família achar a cabeça grande, mesmo com a curva estável e o desenvolvimento normal do bebê",
  "solicitar ultrassonografia transfontanela e agendar retorno em 30 dias para reavaliar a curva antes de liberar o seguimento habitual da criança"]),
7: ("investigar com neuroimagem (ultrassonografia transfontanela) e encaminhar, pois o cruzamento ascendente com sinais de alarme é patológico",
 ["solicitar apenas um hemograma e aguardar a resolução espontânea do abaulamento da fontanela tensa do lactente",
  "atribuir o crescimento craniano ao aleitamento materno e recomendar o desmame antes mesmo de reavaliar a curva",
  "tranquilizar a família e reavaliar só em 6 meses, atribuindo o quadro a macrocefalia familiar benigna apesar dos vômitos e da fontanela tensa e cheia",
  "iniciar restrição hídrica e diurético empírico para reduzir a pressão intracraniana antes de solicitar qualquer exame de imagem do crânio da criança"]),
8: ("confirmar a medida com técnica e curva adequadas, investigar causas (incluindo infecções congênitas) e encaminhar para o seguimento devido",
 ["iniciar reabilitação motora intensiva de imediato, sem qualquer investigação etiológica da microcefalia do bebê",
  "considerar apenas variação normal e não investigar, ignorando a história materna de exantema durante a gestação",
  "atribuir o quadro exclusivamente ao tipo de parto e dispensar exames, mantendo somente o acompanhamento clínico da criança na unidade básica",
  "suspender a vacinação de rotina da criança até que a causa da microcefalia seja completamente esclarecida pela equipe especializada de referência"]),
9: ("medir com fita inelástica pela glabela e pela proeminência occipital, repetir a aferição e valorizar a tendência ao longo de várias consultas",
 ["abandonar a curva de referência e comparar o valor apenas com o perímetro cefálico dos irmãos mais velhos dele",
  "considerar qualquer valor acima da média como indicação imediata de tomografia de crânio, sem nenhuma outra análise",
  "confiar sempre em uma única medida isolada do perímetro cefálico, já que a técnica de aferição não altera de forma relevante o resultado obtido",
  "medir passando a fita sobre as orelhas, buscando a maior circunferência disponível, sem se preocupar com os pontos de referência ósseos do crânio"]),
10: ("orientar sobre o caráter benigno das regurgitações, manter o aleitamento e adotar medidas posturais, sem indicar nenhuma medicação antirrefluxo",
 ["solicitar endoscopia digestiva alta de imediato para confirmar o diagnóstico antes de qualquer orientação à mãe",
  "suspender o aleitamento materno e introduzir fórmula espessada obrigatória para conter logo as regurgitações",
  "iniciar inibidor de bomba de prótons de rotina para todo lactente que regurgita, mesmo com bom ganho de peso e exame físico completamente normal",
  "introduzir domperidona em dose plena para acelerar o esvaziamento gástrico e cessar rapidamente as regurgitações do lactente saudável e bem ativo"]),
11: ("reconhecer sinais de alarme que sugerem doença do refluxo (DRGE), e não refluxo fisiológico, o que justifica investigação e encaminhamento",
 ["iniciar apenas medidas posturais e considerar o quadro benigno, ignorando a recusa alimentar e a hematêmese",
  "atribuir todos os sintomas à técnica de amamentação e dispensar qualquer investigação complementar do bebê",
  "tranquilizar a família como 'regurgitador feliz' e apenas reavaliar em três meses, mesmo diante do baixo ganho de peso e da hematêmese observada",
  "indicar desmame precoce como única medida necessária, sem avaliar o ganho de peso nem investigar os sintomas respiratórios recorrentes do lactente"]),
12: ("manter o bebê em decúbito dorsal para dormir, evitar a superalimentação, fazer a eructação e mantê-lo mais aprumado após cada uma das mamadas",
 ["reduzir drasticamente o volume total diário das mamadas, mesmo com o ganho de peso do bebê já bem adequado",
  "introduzir cereais no leite de um lactente de 2 meses para espessar as mamadas e conter logo a regurgitação",
  "colocar o bebê para dormir em decúbito ventral, pois essa posição reduziria as regurgitações e seria a mais indicada para o lactente com refluxo",
  "elevar a cabeceira do berço com travesseiros durante o sono e manter o bebê deitado logo após as mamadas para diminuir as regurgitações do refluxo"]),
13: ("considerar alergia à proteína do leite de vaca, orientando dieta de exclusão materna de leite e derivados, com a manutenção do aleitamento",
 ["indicar inibidor de bomba de prótons como tratamento definitivo, atribuindo os sintomas apenas ao refluxo",
  "suspender de imediato o aleitamento materno e prescrever fórmula comum de leite de vaca para esse lactente",
  "assumir refluxo fisiológico e apenas reassegurar a mãe, ignorando o sangue nas fezes, o eczema e a história familiar importante de atopia do bebê",
  "iniciar corticoide sistêmico prolongado para tratar o eczema como primeira e única medida, sem modificar a dieta materna nem reavaliar a evolução"]),
14: ("trata-se de constipação funcional, um diagnóstico clínico por fezes endurecidas, retenção e escape, sem sinais de alarme para causa orgânica",
 ["é um padrão evacuatório normal para a idade, que dispensa qualquer orientação ou tratamento para a criança",
  "trata-se de diarreia paradoxal por infecção intestinal, com indicação de antibiótico oral para essa criança",
  "o quadro indica obrigatoriamente doença de Hirschsprung e exige biópsia retal imediata, mesmo sem atraso na eliminação de mecônio ao nascer",
  "o escape fecal indica abuso sexual como causa presumida até prova em contrário, devendo-se notificar antes de qualquer abordagem clínica do caso"]),
15: ("orientar dieta com fibras e hidratação, treino de toalete e laxante osmótico (polietilenoglicol) de forma regular e prolongada, sem recaída",
 ["recomendar enema diário por tempo indefinido como estratégia padrão de manutenção da criança constipada",
  "prescrever só mudança de dieta por poucos dias, sem laxante nem seguimento, confiando na melhora sozinha",
  "iniciar laxante estimulante em altas doses de forma contínua como primeira escolha permanente do tratamento da constipação funcional da criança",
  "suspender o laxante osmótico assim que ocorrer a primeira evacuação normal, encerrando o tratamento antes de consolidar o hábito intestinal saudável"]),
16: ("explicar que o escape decorre de constipação com retenção e transbordamento, tratando com desimpactação, laxante e apoio sem qualquer punição",
 ["recomendar a restrição hídrica para reduzir a produção de fezes e diminuir os episódios de escape da criança",
  "afirmar que se trata de um problema psiquiátrico isolado, sem qualquer relação com a constipação já crônica",
  "orientar punição consistente a cada episódio de escape, para corrigir o que a família interpreta como um comportamento intencional do menino",
  "suspender qualquer tratamento intestinal e encaminhar apenas para reforço escolar, atribuindo o escape à desatenção e à preguiça da criança"]),
17: ("reconhecer sinais de alarme (mecônio tardio, distensão, déficit de crescimento e saída explosiva ao toque) e encaminhar para a investigação",
 ["recomendar somente massagem abdominal e reavaliação em 6 meses, adiando a investigação da constipação",
  "iniciar o treino de toalete precoce como conduta principal no recém-nascido, apesar dos sinais de alarme",
  "tratar como constipação funcional simples apenas com orientação dietética e laxante osmótico, apesar do início muito precoce dos sintomas do bebê",
  "tranquilizar a família afirmando que é o intestino preso normal do recém-nascido, sem valorizar a distensão nem o baixo ganho de peso da criança"]),
18: ("aumentar a frequência de troca das fraldas, limpar suavemente a pele, mantê-la seca e aplicar creme de barreira nas superfícies acometidas",
 ["suspender o banho diário e evitar qualquer creme de barreira na região das fraldas do bebê para não abafar",
  "prescrever antibiótico oral de rotina para toda dermatite de fraldas, mesmo sem sinal de infecção associada",
  "iniciar corticoide potente de uso prolongado como primeira medida na área de fraldas para reduzir rapidamente o eritema das superfícies convexas",
  "aplicar talco em pó em grande quantidade após cada troca para manter a pele bem seca, apesar do risco de aspiração pelo lactente durante o cuidado"]),
19: ("dermatite por candidíase, sugerida pelo acometimento das dobras e pelas lesões satélites, indicando antifúngico tópico e cuidados de pele",
 ["dermatite irritativa simples, que sempre poupa as dobras, tratada apenas com creme de barreira e trocas",
  "impetigo bolhoso da área de fraldas, com indicação obrigatória de corticoide sistêmico e antibiótico oral",
  "psoríase invertida da região inguinal, com indicação de imunossupressor sistêmico imediato antes de qualquer tratamento tópico local da pele do bebê",
  "dermatite seborreica exclusiva da região das fraldas, tratada com antifúngico oral prolongado em vez de medidas tópicas na pele já bastante acometida"]),
20: ("explicar que é condição benigna e autolimitada, orientando higiene suave, emolientes para amolecer as crostas e, se preciso, antifúngico leve",
 ["iniciar antibiótico oral de rotina por presumir infecção bacteriana extensa, mesmo sem sinais inflamatórios",
  "suspender o aleitamento materno por suspeita de alergia grave, atribuindo as placas amareladas à dieta da mãe",
  "prescrever corticoide sistêmico prolongado para resolver rapidamente as crostas do couro cabeludo do lactente com o típico aspecto de crosta láctea",
  "indicar a remoção forçada e vigorosa das crostas com espátula a cada troca, para acelerar a melhora estética do couro cabeludo do lactente pequeno"]),
21: ("hidratar a pele com emolientes, dar banhos rápidos e mornos, usar corticoide tópico de baixa potência nas crises e evitar os desencadeantes",
 ["evitar completamente qualquer hidratante para não abafar a pele atópica, usando só o corticoide nas crises",
  "prescrever corticoide oral prolongado como tratamento de base da dermatite atópica leve desse lactente novo",
  "usar corticoide tópico de alta potência de forma contínua e indefinida na face do lactente para controlar o prurido e a descamação da pele atópica",
  "recomendar banhos muito quentes e demorados para aliviar o prurido, mesmo que isso resseque ainda mais a pele já bastante atópica dessa criança"]),
22: ("dar banhos rápidos e mornos com produtos suaves, hidratar com emolientes, trocar as fraldas com frequência e evitar a exposição solar direta",
 ["evitar qualquer creme de barreira na área de fraldas para não obstruir os poros da pele fina do bebê novo",
  "usar talco em pó abundante em toda troca para secar bem a área de fraldas, mesmo com o risco de aspiração",
  "dar banhos longos e quentes diários com sabonetes antissépticos fortes para higienizar bem a pele delicada do recém-nascido de um mês de vida",
  "aplicar protetor solar químico em toda a pele já nas primeiras semanas de vida como principal medida de proteção contra o sol para o recém-nascido"]),
23: ("tratar a constipação associada, pois a disfunção intestinal e vesical favorece a ITU de repetição, com hidratação e bons hábitos miccionais",
 ["indicar cirurgia antirrefluxo mesmo sem refluxo vesicoureteral significativo na investigação já realizada",
  "afirmar que a constipação não tem relação com as infecções urinárias e focar somente no uso do antibiótico",
  "suspender a ingestão de líquidos para reduzir a produção de urina e, assim, tentar diminuir a frequência das infecções urinárias da menina",
  "manter antibioticoprofilaxia contínua e indefinida como única medida, ignorando a constipação crônica e os hábitos miccionais inadequados da criança"]),
24: ("estimular as micções regulares e programadas, o esvaziamento completo da bexiga, a boa hidratação e evitar o adiamento das idas ao banheiro",
 ["indicar antibiótico contínuo como substituto de qualquer mudança comportamental dos hábitos miccionais",
  "recomendar que a criança urine só quando houver urgência intensa, poucas vezes ao longo de todo o seu dia",
  "orientar a criança a segurar a urina o máximo possível para treinar e fortalecer a bexiga, reduzindo assim a frequência das micções ao longo do dia",
  "restringir a ingestão de líquidos durante todo o dia escolar para evitar que a criança precise usar o banheiro enquanto está longe de casa na escola"]),
25: ("orientar limpeza da frente para trás após evacuar, evitar banhos de espuma e irritantes locais e manter boa hidratação e hábitos miccionais",
 ["manter a limpeza de trás para frente após evacuar, achando que o sentido da higiene não muda o risco de ITU",
  "usar sabonetes antissépticos fortes na região genital diariamente para eliminar as bactérias e evitar a ITU",
  "recomendar duchas vaginais internas regulares para higienizar melhor a região genital e prevenir novos episódios de infecção urinária na menina",
  "restringir totalmente a ingestão de água ao longo do dia para reduzir a frequência urinária e, com isso, tentar evitar novas infecções urinárias"]),
26: ("explicar que o prepúcio não retrátil é fisiológico no lactente e não deve ser forçado, mantendo somente a higiene suave da região genital",
 ["suspender o banho da região genital para evitar a irritação do prepúcio durante o período de uso de fralda",
  "indicar circuncisão de urgência para o menino que teve um só episódio de infecção urinária ao longo do ano",
  "orientar a retração forçada e vigorosa do prepúcio em todas as trocas de fralda para tentar prevenir novas infecções urinárias no menino lactente",
  "aplicar corticoide tópico potente por tempo indefinido de rotina em todos os lactentes com prepúcio ainda não retrátil observado durante a consulta"]),
27: ("acolher com confidencialidade, orientar métodos contraceptivos eficazes e a dupla proteção com preservativo, sem exigir a presença dos pais",
 ["prescrever o contraceptivo sem qualquer orientação sobre a prevenção de infecções sexualmente transmissíveis",
  "orientar apenas o método comportamental da tabelinha como o único recurso contraceptivo para a adolescente",
  "recusar qualquer orientação até que a adolescente retorne obrigatoriamente acompanhada dos pais ou de um responsável legal maior de idade ao serviço",
  "afirmar que os adolescentes não devem receber orientação contraceptiva sob nenhuma circunstância antes de atingirem a maioridade legal no país"]),
28: ("oferecer a contracepção de emergência o quanto antes, pois a eficácia é maior com menor intervalo, e orientar método regular e prevenção de ISTs",
 ["substituir a contracepção de emergência por um antibiótico profilático como método principal de prevenção",
  "condicionar a contracepção de emergência a um teste de gravidez imediato com resultado negativo antes de tudo",
  "afirmar que a contracepção de emergência só pode ser usada dentro das primeiras duas horas após a relação sexual desprotegida da adolescente",
  "recusar a contracepção de emergência por objeção pessoal do profissional, sem oferecer alternativa nem encaminhar a jovem a um outro serviço"]),
29: ("acolher sem julgamento e garantir pré-natal com o mesmo cuidado técnico, atento a nutrição, pré-eclâmpsia, prematuridade e ao suporte social",
 ["focar apenas em recriminar a gestação precoce da jovem, sem estruturar o acompanhamento clínico do caso",
  "negar o atendimento pré-natal até que a adolescente compareça acompanhada de um responsável legal na consulta",
  "oferecer um pré-natal simplificado por ser adolescente, com menos consultas e exames do que o preconizado para as demais gestantes do serviço",
  "encaminhar diretamente para a interrupção da gestação como conduta padrão do serviço diante de toda gestante adolescente atendida na unidade"]),
30: ("reservar parte da consulta para o atendimento a sós, com sigilo, abordando saúde sexual, uso de substâncias e saúde mental do adolescente",
 ["encaminhar todo adolescente a serviços especializados, sem qualquer abordagem preventiva na atenção básica",
  "quebrar rotineiramente o sigilo, relatando aos pais tudo o que foi conversado com o adolescente na consulta",
  "realizar toda a consulta apenas na presença dos pais, sem reservar um espaço privado para conversar a sós com o adolescente atendido naquele dia",
  "abordar somente as queixas físicas do adolescente, evitando temas como sexualidade e saúde mental por considerá-los constrangedores na consulta"]),
31: ("no Brasil, o aleitamento é contraindicado na mãe com HIV, orientando fórmula infantil e inibição da lactação, mesmo com carga indetectável",
 ["recomendar amamentar só nos primeiros dias para garantir o colostro e depois iniciar a fórmula infantil",
  "orientar o aleitamento misto, alternando leite materno e fórmula infantil, como uma opção segura para a mãe",
  "liberar o aleitamento materno exclusivo, pois a carga viral indetectável eliminaria totalmente o risco de transmissão vertical pelo leite materno",
  "permitir o aleitamento cruzado por outra mulher soronegativa como alternativa preferencial ao uso de fórmula infantil para alimentar o bebê"]),
32: ("o aleitamento é contraindicado na infecção materna por HTLV, pelo risco de transmissão pelo leite, orientando fórmula e a inibição da lactação",
 ["orientar o aleitamento misto para reduzir pela metade o risco de transmissão do HTLV pelo leite ao bebê",
  "recomendar só a pasteurização caseira do leite materno para a mãe seguir amamentando o seu bebê em casa",
  "liberar o aleitamento materno exclusivo, pois o HTLV não seria transmitido pelo leite materno e não representaria risco ao recém-nascido saudável",
  "permitir o aleitamento cruzado por outra mulher como alternativa preferencial ao uso de fórmula infantil no contexto do HTLV materno confirmado"]),
33: ("o uso de cocaína/crack contraindica o aleitamento durante o uso, pela passagem ao leite, orientando alternativa alimentar e apoio à mãe usuária",
 ["orientar amamentar apenas algumas horas após o uso da droga, achando o aleitamento seguro nesse intervalo",
  "liberar o aleitamento normalmente, pois as drogas ilícitas não passariam para o leite materno em quantidade",
  "manter o aleitamento e apenas recomendar que a mãe aumente a ingestão de água para diluir a droga que passa para o leite materno do bebê",
  "suspender o aleitamento sem qualquer abordagem sobre o tratamento da dependência química materna nem sobre o cuidado integral da criança"]),
34: ("infecções comuns como o resfriado não contraindicam o aleitamento, que deve ser mantido; a maioria dos medicamentos usuais também é compatível",
 ["a mastite é sempre uma contraindicação absoluta e definitiva ao aleitamento, exigindo o desmame imediato",
  "a icterícia fisiológica do recém-nascido é contraindicação ao aleitamento e obriga à fórmula temporária",
  "qualquer infecção respiratória materna, como o resfriado comum, contraindicaria o aleitamento e exigiria a sua suspensão temporária por precaução",
  "o uso de qualquer medicamento pela mãe contraindica automaticamente o aleitamento, que só poderia ser retomado após o fim completo do tratamento"]),
35: ("manter o aleitamento, orientando cessar ou reduzir o tabagismo, não fumar perto da criança e evitar amamentar logo após o consumo de álcool",
 ["indicar o desmame imediato e definitivo a qualquer mãe que fume ou consuma bebida alcoólica de forma eventual",
  "liberar o consumo elevado e frequente de álcool durante o aleitamento sem qualquer ressalva à mãe nutriz",
  "orientar a mãe a fumar dentro do quarto do bebê, pois o risco da exposição ao tabaco seria irrelevante para o lactente que já mama e cresce bem",
  "afirmar que o tabagismo e o álcool não têm nenhuma relação com o cuidado do lactente e dispensar qualquer orientação sobre esses hábitos maternos"]),
36: ("suplementar vitamina D desde a primeira semana de vida até os 24 meses, em dose profilática, mesmo no lactente em aleitamento materno exclusivo",
 ["suplementar vitamina D em dose única anual, de forma mais prática, em vez da administração diária habitual",
  "suplementar vitamina D apenas nos recém-nascidos prematuros, dispensando os que nasceram a termo e saudáveis",
  "não suplementar vitamina D, pois o leite materno exclusivo já forneceria a quantidade suficiente da vitamina para o lactente saudável em casa",
  "suplementar vitamina D apenas a partir dos 6 meses, junto com o início da alimentação complementar, e mantê-la somente até os 12 meses de idade"]),
37: ("iniciar a suplementação profilática de ferro no lactente a termo com peso adequado, dos 3 aos 6 meses até os 24 meses, em dose profilática",
 ["usar ferro apenas em dose terapêutica alta desde o nascimento, independentemente do peso do bebê ao nascer",
  "não suplementar ferro em nenhum lactente a termo, pois a alimentação complementar já traria o ferro preciso",
  "suplementar ferro somente após a confirmação de anemia por hemograma, dispensando a profilaxia nos lactentes ainda sem qualquer sinal de anemia",
  "suspender a alimentação complementar e substituí-la exclusivamente pela suplementação de ferro em gotas até que a criança complete o primeiro ano"]),
38: ("prematuros e recém-nascidos de baixo peso precisam de ferro iniciado mais cedo e em doses ajustadas ao peso, pelo maior risco de deficiência",
 ["prematuros seguem exatamente o mesmo esquema de ferro dos nascidos a termo, sem nenhum ajuste de dose",
  "a suplementação de ferro é dispensável no prematuro em aleitamento exclusivo, pois o leite supriria tudo",
  "prematuros não devem receber ferro no primeiro ano de vida por risco de sobrecarga, bastando reforçar o ferro na dieta da mãe que amamenta o bebê",
  "a suplementação de ferro no prematuro só deve começar depois dos 12 meses de idade, seguindo o mesmo momento indicado para o bebê nascido a termo"]),
39: ("a vitamina K é administrada de rotina ao nascer para prevenir a doença hemorrágica do recém-nascido, devendo constar do registro neonatal",
 ["a vitamina K só é dada aos recém-nascidos que já apresentam algum sangramento nas primeiras horas de vida",
  "era uma dose de antibiótico profilático administrada de rotina a todos os recém-nascidos logo após o parto",
  "a injeção era de vitamina D, aplicada em dose única ao nascer para cobrir toda a necessidade do primeiro ano de vida do bebê nascido saudável",
  "trata-se de um suplemento de ferro injetável administrado de rotina para prevenir a anemia neonatal em todos os recém-nascidos da maternidade"]),
40: ("manter o aleitamento e as suplementações de ferro e vitamina D, oferecer alimentos variados e evitar o leite de vaca e o mel antes de 1 ano",
 ["substituir o leite materno pelo leite de vaca integral como a bebida principal já a partir dos seis meses",
  "suspender as suplementações de ferro e de vitamina D assim que a alimentação complementar for iniciada",
  "acrescentar sal e açúcar às preparações do lactente para estimular a aceitação dos novos alimentos durante a introdução alimentar desta fase",
  "oferecer mel para adoçar as papas, por ser um produto natural considerado seguro para o lactente em qualquer idade da criança, mesmo bem pequena"]),
41: ("respeitar o sigilo do adolescente e manter a informação confidencial, pois não há risco que justifique a quebra, estimulando o diálogo familiar",
 ["recusar o atendimento por considerar que o adolescente não pode ter conversas sigilosas sem os pais junto",
  "condicionar todo o atendimento à autorização prévia dos pais para qualquer conversa reservada com o jovem",
  "informar imediatamente os pais sobre a vida sexual do adolescente, independentemente de haver ou não risco à sua vida ou à de terceiros",
  "registrar a informação de forma visível no prontuário para que qualquer familiar tenha acesso ao conteúdo relatado pelo adolescente na consulta"]),
42: ("quebrar o sigilo de forma responsável para proteger o adolescente, envolvendo a família e a rede de cuidado, pois há risco iminente à vida",
 ["manter o sigilo absoluto e não envolver ninguém, respeitando estritamente o pedido do adolescente em crise",
  "informar apenas a escola sobre o risco relatado, sem envolver a família nem os serviços de saúde mental",
  "apenas orientar verbalmente e liberar o adolescente sem acionar a família nem a rede de apoio em saúde mental diante do risco de suicídio relatado",
  "encaminhar somente para retorno ambulatorial em algumas semanas, sem adotar qualquer medida imediata de proteção à vida do jovem que está em crise"]),
43: ("notificar obrigatoriamente a suspeita ao Conselho Tutelar, conforme o ECA, para proteger a criança, independentemente de confirmação diagnóstica",
 ["notificar o Conselho Tutelar somente se os pais autorizarem expressamente o encaminhamento da suspeita",
  "aguardar a confirmação definitiva do diagnóstico de maus-tratos antes de fazer qualquer notificação do caso",
  "resolver a situação apenas com orientação verbal aos pais, sem notificar o Conselho Tutelar sobre a suspeita de maus-tratos observada na criança",
  "encaminhar a criança exclusivamente para acompanhamento psicológico, sem realizar a notificação obrigatória da suspeita de maus-tratos ao órgão"]),
44: ("atender e testar respeitando a autonomia e o sigilo do adolescente, sem exigir a presença ou a autorização dos pais, pois não há risco grave",
 ["encaminhar o adolescente para outro serviço apenas para evitar atendê-lo desacompanhado dos pais na UBS",
  "exigir a presença de um responsável legal para qualquer testagem, independentemente da maturidade do jovem",
  "recusar o atendimento e a testagem enquanto o adolescente não trouxer uma autorização por escrito assinada pelos pais ou pelo responsável legal",
  "realizar a testagem, mas comunicar obrigatoriamente o resultado aos pais, mesmo sem qualquer situação de risco que justifique a quebra do sigilo"]),
45: ("informar os pais sobre riscos e benefícios, registrar a recusa e, se ela persistir como negligência, acionar a proteção como o Conselho Tutelar",
 ["encerrar o acompanhamento da criança na unidade básica de saúde por causa da recusa vacinal dos pais dela",
  "aceitar passivamente a recusa vacinal, sem qualquer orientação, registro ou medida de proteção à criança",
  "vacinar a criança à força imediatamente, sem qualquer diálogo ou informação aos pais sobre os riscos e benefícios das vacinas do calendário oficial",
  "afirmar que a vacinação é sempre facultativa e que não existe nenhum mecanismo de proteção aplicável diante da recusa vacinal persistente dos pais"]),
}

# ---- part1 puericultura items (idPrefix ped-pueri, keyed by n) ----
P1 = {
1: ("aplicar a segunda dose de rotavírus hoje, se dentro da idade máxima do calendário, e orientar sobre os efeitos gastrointestinais leves",
 ["substituir a vacina de rotavírus por imunoglobulina intramuscular mensal para proteger contra a gastroenterite",
  "adiar a vacina de rotavírus para depois dos 12 meses, ainda que a idade máxima recomendada já tenha passado",
  "contraindicar qualquer dose de rotavírus hoje porque a criança já recebeu a pentavalente e a polio inativada na mesma consulta de rotina",
  "aplicar a terceira dose de rotavírus agora, mesmo sem ter recebido a segunda, para tentar compensar o suposto atraso no esquema da criança"]),
2: ("reforçar que o aleitamento está adequado, tranquilizar a mãe e manter o acompanhamento de puericultura, sem complementar com fórmula infantil",
 ["solicitar uma mamografia materna de urgência antes de decidir se o aleitamento realmente deve ser mantido",
  "orientar chá de erva-doce entre as mamadas para fortalecer o leite materno e melhorar o ganho de peso do bebê",
  "iniciar fórmula infantil de rotina, pois todo ganho ponderal abaixo de 30 g por dia exigiria complemento independentemente dos demais dados",
  "indicar o desmame completo e a introdução de leite de vaca integral diluído como substituto do leite materno considerado insuficiente pela mãe"]),
3: ("manter o aleitamento e iniciar alimentos in natura amassados, com variedade e fonte de ferro e proteína animal, sem excesso de açúcar ou sal",
 ["oferecer apenas leite de vaca integral como o único complemento alimentar entre os seis e os doze meses",
  "esperar até os 12 meses para oferecer qualquer alimento sólido à criança que está em aleitamento materno",
  "iniciar a alimentação complementar com sucos adoçados e biscoitos como os primeiros alimentos oferecidos ao lactente nessa nova fase da vida",
  "suspender totalmente o aleitamento materno no mesmo dia em que a papa principal for introduzida na alimentação do lactente de seis meses de idade"]),
4: ("classificar como desnutrição aguda/magreza e tratar as intercorrências, elaborar um plano alimentar e articular com a rede de proteção social",
 ["indicar cirurgia bariátrica pediátrica em razão do índice de massa corporal baixo apresentado pela criança",
  "considerar apenas baixa estatura familiar e dar alta sem qualquer intervenção nutricional para essa criança",
  "classificar como obesidade infantil e iniciar de imediato uma dieta restritiva severa para reduzir o peso da criança de três anos de idade",
  "diagnosticar kwashiorkor edematoso típico e indicar albumina venosa de rotina como a única medida terapêutica realmente necessária no caso"]),
5: ("indicar mudança intensiva de estilo de vida, rastrear as comorbidades e acompanhar a pressão arterial e o perfil metabólico dessa criança",
 ["prescrever corticoide para reduzir a acanthosis nigricans cervical em vez de tratar a obesidade do escolar",
  "indicar cirurgia bariátrica de imediato como a primeira medida terapêutica para o escolar de nove anos",
  "liberar sem seguimento, pois a glicemia de jejum ainda não fechou o diagnóstico de diabetes no escolar com obesidade e pressão elevada",
  "iniciar insulina basal de rotina por causa da acanthosis nigricans, mesmo com a glicemia de jejum ainda abaixo de 100 mg/dL na criança avaliada"]),
6: ("reconhecer o atraso de marcos, solicitar avaliação especializada precoce e iniciar a estimulação, investigando as causas conforme a clínica",
 ["indicar apenas suplemento de ômega-3 e reavaliar o desenvolvimento do lactente somente daqui a um ano",
  "aguardar até os 18 meses, sob a justificativa de que cada criança tem o seu tempo, sem intervir por ora",
  "diagnosticar autismo de forma definitiva apenas pela ausência de balbucio aos nove meses, sem qualquer avaliação estruturada do desenvolvimento",
  "solicitar ressonância magnética de rotina em todo lactente antes de iniciar qualquer estimulação ou intervenção sobre o atraso já observado"]),
7: ("tratar com vitamina D em dose terapêutica, corrigir o cálcio se necessário, orientar sol e alimentação e acompanhar a resposta laboratorial",
 ["indicar paratireoidectomia empírica como conduta inicial diante do raquitismo carencial desse lactente",
  "imobilizar os membros superiores por três meses, sem repor a vitamina D, para o alargamento dos punhos",
  "apenas orientar banho de sol, sem qualquer reposição farmacológica, diante da vitamina D tão baixa e das alterações ósseas já presentes",
  "iniciar bifosfonato intravenoso como primeira linha de tratamento do raquitismo carencial nesse lactente com deficiência grave de vitamina D"]),
8: ("iniciar ferro oral em dose terapêutica, orientar a redução do leite de vaca em excesso e uma dieta com ferro biodisponível, e reavaliar depois",
 ["solicitar um mielograma antes de qualquer tentativa de tratamento com ferro oral no lactente com anemia",
  "iniciar vitamina B12 isolada como tratamento da microcitose com ferritina baixa desse lactente pálido",
  "transfundir concentrado de hemácias de rotina em todo valor de hemoglobina abaixo de 9 g/dL, mesmo na criança estável e acompanhada em ambulatório",
  "suspender o ferro e indicar apenas alimentação real, sem suplemento, mesmo com a hemoglobina em 8,9 g/dL nesse lactente com palidez importante"]),
9: ("orientar sobre a cólica e o choro do lactente, oferecer suporte à amamentação e estratégias de acalento, mantendo o acompanhamento habitual",
 ["iniciar um opioide para promover a sedação do lactente e reduzir os episódios de choro do fim da tarde",
  "solicitar tomografia de crânio de rotina antes mesmo de orientar a família sobre o manejo do choro",
  "trocar imediatamente por fórmula extensamente hidrolisada em todo lactente com choro vespertino, mesmo com o ganho de peso perfeitamente adequado",
  "indicar fundo de olho sob narcose como a primeira investigação a ser realizada no lactente com choro vespertino e bom ganho de peso na consulta"]),
10: ("suspender o açúcar da mamadeira noturna, orientar a higiene oral e a avaliação odontopediátrica e evitar líquidos adoçados na hora de deitar",
 ["manter a mamadeira noturna adoçada, sob o argumento de que seria a única forma de a criança adormecer",
  "indicar antibiótico contínuo para esterilizar a boca e conter o avanço das múltiplas cáries da criança",
  "aguardar a erupção da dentição permanente para qualquer cuidado, sem nenhuma mudança do hábito da mamadeira noturna adoçada da criança pequena",
  "extrair todos os dentes decíduos já na primeira consulta odontológica, sem qualquer plano de tratamento ou mudança prévia de hábito alimentar"]),
11: ("orientar a segurança no domicílio: proteger escadas e tomadas, evitar engasgo com alimentos esféricos e supervisionar o banho e a cadeirinha",
 ["dispensar o uso da cadeirinha no carro sempre que o trajeto for curto, por considerar o risco pequeno",
  "deixar baldes com água no chão do quintal para a criança brincar enquanto engatinha pela casa toda",
  "liberar mel à vontade para fortalecer a imunidade do lactente de onze meses que engatinha e explora o ambiente doméstico com muita frequência",
  "oferecer amendoim inteiro como o lanche preferencial do lactente de onze meses, apesar do risco de engasgo próprio dessa faixa etária da criança"]),
12: ("encaminhar para avaliação endocrinológica de puberdade precoce e investigar o eixo hormonal, sem apenas observar a criança até os 10 anos",
 ["indicar ooforectomia empírica como conduta inicial para conter a progressão puberal precoce da menina",
  "iniciar anticoncepcional oral combinado na unidade básica como a primeira medida diante da telarca",
  "considerar o quadro sempre fisiológico antes dos dez anos e dar alta sem investigação na menina com telarca e avanço da idade óssea observado",
  "prescrever hormônio de crescimento para aproveitar a aceleração estatural atual da menina com sinais puberais e idade óssea bastante avançada"]),
13: ("orientar a família a evitar a punição, restringir líquidos à noite, usar um diário miccional e considerar alarme ou desmopressina se preciso",
 ["indicar cirurgia de alongamento vesical como a primeira linha de tratamento da enurese noturna do menino",
  "orientar a punição a cada episódio noturno para criar responsabilidade na criança, reforçando os pais",
  "iniciar um antipsicótico noturno de rotina para controlar a enurese noturna primária monossintomática nesse menino de seis anos e meio de idade",
  "solicitar uretrocistografia miccional em todos os casos antes de qualquer medida comportamental para a enurese primária monossintomática do menino"]),
14: ("encaminhar com urgência para avaliação auditiva diagnóstica e reforçar a vigilância do desenvolvimento e da visão, sem esperar até os 12 meses",
 ["orientar apenas estimular a criança com a televisão em volume bem alto para testar a audição do bebê",
  "indicar implante coclear imediato, sem qualquer diagnóstico audiológico prévio, para o lactente atual",
  "aguardar o surgimento da fala aos dois anos de idade para só então investigar a audição do lactente sem resposta a sons altos em casa",
  "prescrever antibiótico ótico empírico prolongado, sem avaliação diagnóstica, diante da ausência de resposta do lactente aos sons altos do ambiente"]),
15: ("tratar a enterobíase com mebendazol ou albendazol conforme o protocolo, reforçar a higiene de mãos e unhas e considerar tratar os conviventes",
 ["prescrever apenas pomada de corticoide local por três meses, sem antiparasitário, para a irritação anal",
  "iniciar vancomicina oral por suspeita de colite pseudomembranosa diante do prurido anal noturno atual",
  "solicitar colonoscopia em todos os casos de prurido anal noturno antes de iniciar qualquer tratamento antiparasitário empírico no pré-escolar",
  "internar a criança para realizar parasitológico seriado por sete dias antes de qualquer tratamento empírico típico da enterobíase na infância"]),
16: ("garantir a escuta confidencial conforme a boa prática, orientar contracepção e prevenção de ISTs, atualizar a vacina de HPV e indicar a rede",
 ["prescrever antibiótico contínuo profilático para todas as ISTs sem qualquer indicação clínica específica",
  "indicar apenas a abstinência sexual, sem qualquer informação sobre a prevenção de ISTs e de gravidez",
  "recusar qualquer orientação contraceptiva até haver autorização escrita dos pais, mesmo diante de um adolescente maduro que já busca o cuidado",
  "realizar exame especular compulsório em todo adolescente já na primeira consulta de rotina, mesmo sem qualquer indicação clínica para o exame"]),
}
