/**
 * Flashcards Cardiologia · Car3
 * Fonte exclusiva: data/_extract_cardio/Car3-full.txt e snips-car3/
 */
const fs = require("fs");
const path = require("path");

const deck = (id, name, cards) => ({ id, name, specialty: "clinica", cards });
const card = (front, back) => ({ front, back });

const newDecks = [
  deck("cardio-fa-flutter", "Fibrilação atrial · flutter atrial", [
    card("FA — critérios eletrocardiográficos?", "R-R irregular · ausência de onda P ou de atividade atrial regular · QRS geralmente estreito · FC usualmente 90–170 bpm"),
    card("FA — mecanismo e frequência atrial?", "Múltiplos pequenos circuitos de reentrada funcional · átrios em 400–600/min · NAV filtra os estímulos e costuma deixar passar 90–170/min"),
    card("FA — por que reduz o débito cardíaco?", "Taquicardia reduz enchimento ventricular e aumenta consumo de O₂ · perda da contração atrial reduz 20–40% do enchimento diastólico"),
    card("FA — local preferido de trombo e principal embolia?", "Apêndice atrial esquerdo/auriculeta · AVE isquêmico cardioembólico é a manifestação embólica mais frequente"),
    card("FA — classificação pela duração?", "Paroxística · reverte até 7 dias · persistente · > 7 dias · persistente de longa duração · > 1 ano · permanente · decisão de não restaurar/manter ritmo sinusal"),
    card("CHA₂DS₂-VASc — componentes e pontos?", "ICC 1 · HAS 1 · idade ≥ 75 anos 2 · DM 1 · AVC/AIT/tromboembolismo 2 · doença vascular 1 · idade 65–74 anos 1 · sexo feminino 1"),
    card("CHA₂DS₂-VASc — quando anticoagular conforme o texto?", "Homem 0 ou mulher 1 · não anticoagular · homem 1 ou mulher 2 · considerar · homem ≥ 2 ou mulher ≥ 3 · anticoagular"),
    card("FA valvar/alto risco — quem anticoagular sem escore?", "Estenose mitral moderada-grave · prótese mecânica ou biológica implantada há 3–6 meses · cardiomiopatia hipertrófica com FA · CHA₂DS₂-VASc é para FA não valvar"),
    card("FA de alto risco cardioembólico — anticoagulação após retorno ao ritmo?", "Indefinida · mesmo após ritmo sinusal, pois episódios assintomáticos recorrentes de FA podem formar trombos"),
    card("HAS-BLED > 3 na FA — contraindica anticoagulação?", "Não · sinaliza alto risco hemorrágico e exige corrigir fatores modificáveis, avaliar adesão e individualizar a conduta"),
    card("Quais DOAC o Car3 cita e qual perfil de sangramento?", "Dabigatrana, rivaroxabana, apixabana e edoxabana · ≥ eficácia do warfarin · menos hemorragia intracraniana · dabigatrana/rivaroxabana: mais hemorragia digestiva"),
    card("Como iniciar anticoagulação com warfarin × DOAC na FA?", "Warfarin: heparina/enoxaparina até INR 2–3, depois suspender heparina · DOAC: início imediato, sem heparina de ponte nem monitorização de INR/PTTa"),
    card("FA instável — conduta e energia bifásica citada?", "Cardioversão elétrica sincronizada imediata · 100–200 J · sem necessidade de anticoagulação prévia"),
    card("FA estável — controle de frequência: meta e fármacos?", "FC de repouso < 110 bpm · betabloqueador é preferido se possível · diltiazem/verapamil ou digitálico são alternativas conforme o contexto"),
    card("FA estável — quando preferir inicialmente controle do ritmo?", "Primeiro episódio com fator reversível · sintomas persistentes apesar de controlar FC · impossibilidade de atingir a FC-alvo"),
    card("O que é a estratégia pill-in-the-pocket?", "Propafenona ou flecainida VO no início dos sintomas de FA paroxística, no não cardiopata · 30 min antes, usar inibidor do NAV para evitar flutter com condução rápida"),
    card("Quem não pode usar propafenona/flecainida no controle do ritmo?", "Portadores de cardiopatia estrutural, como DAC, disfunção sistólica ou HVE importante"),
    card("FA > 48 h ou duração desconhecida — cardioversão segura?", "ETE para pesquisar trombo · sem trombo, cardioverter · com trombo ou sem ETE, anticoagular 3–4 semanas antes · após cardioversão, manter ao menos 4 semanas se baixo risco"),
    card("Flutter típico — ECG e mecanismo?", "Ondas F 250–350/min, tipicamente ~300 · sem linha isoelétrica, dente de serra em D2/D3/aVF · macrorreentrada no átrio direito dependente do istmo"),
    card("Flutter típico — condução AV 2:1 × 4:1?", "2:1 · FC ~150 bpm · 4:1 · FC ~75 bpm · 4:1 ocorre com doença NAV ou inibidores do NAV"),
    card("Flutter instável × estável sintomático — abordagem?", "Instável · cardioversão sincronizada 50 J, sucesso ~90% · estável · reduzir condução AV com betabloqueador, verapamil, diltiazem ou digital e considerar cardioversão"),
    card("O que é overdrive pacing no flutter?", "Estimulação atrial ~10% acima da FC do flutter · ao reduzir a frequência, ~70% voltam ao sinusal ou mudam para FA · muito usado no pós-operatório"),
  ]),
  deck("cardio-tvs-svt", "TSVP · WPW · taquicardias ventriculares", [
    card("Taquicardia com QRS ≥ 120 ms — regra prática?", "Considerar taquicardia ventricular até prova em contrário · diferenciais incluem TSV com aberrância, TAVR antidrômica e FA com WPW"),
    card("TV monomórfica — critérios no ECG?", "QRS alargado e aberrante ≥ 120 ms · mesma morfologia de QRS em cada derivação · R-R regular · FC geralmente > 100–120 bpm"),
    card("TV sustentada × não sustentada?", "Sustentada · duração > 30 s ou causa instabilidade independentemente da duração · não sustentada · < 30 s e sem instabilidade"),
    card("TV monomórfica × TSV com aberrância — achados que favorecem TV?", "Ausência de RS em precordiais · RS > 100 ms · dissociação AV · morfologia de V1/V6 incompatível com BRD/BRE típico"),
    card("Critérios de Brugada — princípio central?", "Na TSV com aberrância, a morfologia do QRS é típica de BRD ou BRE · se a morfologia não for típica de bloqueio de ramo, favorece TV"),
    card("TV monomórfica — mecanismo e gatilho usuais?", "Geralmente reentrada em miocárdio doente/fibrose · exige condução lenta e dispersão de refratariedade · gatilho habitual é extrassístole ventricular"),
    card("Torsades de pointes — mecanismo, contexto e arritmia?", "Atividade deflagrada por pós-potenciais precoces · QT longo por drogas, bradicardia, hipocalemia ou hipomagnesemia · TV polimórfica"),
    card("Torsades de pointes — tratamento citado?", "Sulfato de magnésio · mesmo em normomagnesêmicos · suspender droga culpada · isoproterenol em torsades repetitivo por pausas"),
    card("TSVP por reentrada nodal — ECG típico?", "FC 120–220 bpm · início e término súbitos · QRS geralmente estreito · R-R regular · sem P aparente ou pseudo-S em inferiores/pseudo-R’ em V1"),
    card("TSVP por reentrada nodal — substrato e circuito?", "Dupla via nodal · via lenta alfa tem PRE curto · via rápida beta tem PRE longo · extrassístole bloqueia beta, desce por alfa e retorna por beta"),
    card("TSVP por reentrada nodal estável — sequência terapêutica?", "Manobra vagal · adenosina 6 mg IV rápida, repetir 12 mg se necessário · verapamil como segunda escolha · betabloqueador como terceira"),
    card("TSVP por reentrada nodal instável — cardioversão?", "Cardioversão elétrica sincronizada · energia inicial de 150 J"),
    card("Profilaxia e cura da reentrada nodal?", "Profilaxia: digoxina, verapamil, diltiazem ou BB · Definitiva: ablação da via alfa com cura ~95% · risco de BAVT 0–5%"),
    card("TAVR ortodrômica × antidrômica?", "Ortodrômica · desce pelo NAV e sobe pela via acessória · QRS estreito · antidrômica · desce pela via acessória e sobe pelo NAV · QRS alargado"),
    card("TAVR por via acessória — pista ECG de ortodrômica?", "Onda P’ retrógrada logo após o QRS · RP’ < P’R · pode haver alternância da amplitude do QRS"),
    card("WPW em ritmo sinusal — padrão de pré-excitação?", "PR curto < 120 ms + onda delta · a via acessória ativa precocemente o ventrículo fora do His-Purkinje"),
    card("FA com WPW — reconhecimento e risco?", "FC 180–350 bpm · R-R irregular · QRS pré-excitados largos, normais e batimentos de fusão · se FC > 250, risco de degenerar em FV"),
    card("FA com WPW — fármacos contraindicados e escolha?", "Não usar inibidores do NAV: verapamil, diltiazem, digital, betabloqueadores · primeira escolha é procainamida · segunda, ibutilida"),
    card("TAVR antidrômica — droga de escolha?", "Procainamida · não usar inibidores do NAV, pois podem aumentar a condução pela via acessória"),
    card("Taquicardia atrial multifocal — contexto e ECG?", "DPOC descompensada/hipoxemia · ≥ 3 morfologias de P · gênese multifatorial: cor pulmonale, hipoxemia/acidose, hipoK/Mg, teofilina"),
    card("Taquicardia atrial automática — por que não cardioverter?", "Ritmo automático, não reentrante · CVE nunca indicada · BB/verapamil podem reduzir resposta ventricular · grupos IB/IC/III podem tentar reversão"),
  ]),
  deck("cardio-bradi-bav", "Bradiarritmias · bloqueios AV · marca-passo", [
    card("Bradiarritmias — três mecanismos principais?", "Vagotonia · isquemia do nó sinusal/NAV · degeneração do sistema especializado de condução"),
    card("Vagotonia — efeito eletrofisiológico?", "Acetilcolina bloqueia canais de cálcio no nó sinusal/NAV e estimula canais de potássio · bradicardia, menor condução e maior refratariedade AV"),
    card("Bradicardia sinusal por vagotonia/drogas — conduta inicial?", "Corrigir fator precipitante e administrar atropina 0,5–1 mg IV · repetir a cada 5 min até dose máxima de 3 mg"),
    card("Doença do nó sinusal — apresentação de síndrome bradi-taqui?", "FA/flutter/taquicardia atrial paroxística seguidos por bradicardia sinusal importante ou pausas · sugere DNS, sobretudo no idoso"),
    card("Síndrome bradi-taqui — conduta antes de antiarrítmico/cardioversão?", "Implantar MP definitivo DDDR · antiarrítmicos, especialmente amiodarona, podem piorar a função do nó sinusal · DDDR reduz recidiva de FA vs câmara única"),
    card("BAV de 1º grau — alteração eletrocardiográfica?", "PR prolongado por lentificação da condução AV · no contexto de bloqueio de ramo completo pode sinalizar comprometimento do terceiro fascículo"),
    card("BAV de 2º grau Mobitz I — localização e resposta à atropina?", "Quase sempre supra-hissiano/vagotônico · geralmente benigno e responsivo à atropina"),
    card("BAV de 2º grau Mobitz II — localização e conduta?", "Quase sempre intra ou infra-hissiano/degenerativo · não responde à atropina · marca-passo indicado"),
    card("BAV 2:1 — pistas de localização intra/infra-hissiana?", "QRS alargado · ausência de BAV de 1º grau · não resposta ou piora com ergometria ou atropina"),
    card("BAV total — quando MP é sempre indicado?", "Sintomas · escape < 40 bpm · QRS alargado por bloqueio de ramo"),
    card("Bradiarritmias malignas que tendem a necessitar MP?", "DNS sintomática · BAV intra/infra-hissiano ou de alto grau/BAVT · DCIV avançado"),
    card("MP provisório — indicações centrais?", "Bradiarritmia sintomática provável intra/infra-hissiana · bradiarritmia supra-hissiana sem resposta à atropina · situações de alto risco na fase aguda do IAM"),
    card("Colapso circulatório por bradiarritmia — sequência de MP?", "MP transcutâneo imediato para ganhar tempo · depois MP transvenoso, idealmente sem postergar mais de 30–60 min"),
    card("IAM agudo — quais distúrbios indicam MP provisório Classe I?", "Assistolia · Mobitz II · BAVT · bloqueio trifascicular · bloqueio bifascicular novo + BAV 1º · BRE novo + BAV 1º"),
    card("BAVT persistente/intermitente — critérios Classe I para MP definitivo?", "Sintomas · ICC · confusão que melhora com MP provisório · escape < 40 bpm ou pausas > 3 s · pós-ablação AV ou pós-operatório persistente"),
    card("FA/flutter com resposta ventricular lenta — indicação de MP definitivo?", "FC < 40 bpm · pausas > 3 s · ou bradicardia sintomática · modo típico: VVIR"),
    card("O que significa o modo VVI(R)?", "Estimula ventrículo · reconhece QRS · inibe-se se houver QRS · R = ajuste de frequência ao exercício · modo mais simples do MP provisório"),
    card("O que significa o modo DDD?", "Dupla câmara · sensing atrial inibitório e estimulatório · P espontânea inibe estímulo atrial e dispara estímulo ventricular · mais fisiológico"),
    card("Causa transitória × crônica de bradiarritmia — MP?", "Transitória, como IAM/intoxicação/pós-operatório · MP provisório e retirar após recuperação · degenerativa/irreversível ou persistente · MP definitivo"),
  ]),
  deck("cardio-pcr", "PCR · BLS e ACLS", [
    card("PCR — quatro ritmos sem fluxo?", "Fibrilação ventricular · taquicardia ventricular sem pulso · assistolia · atividade elétrica sem pulso (AESP)"),
    card("PCR — ritmos chocáveis × não chocáveis?", "Chocáveis · FV e TV sem pulso · não chocáveis · assistolia e AESP"),
    card("PCR extra-hospitalar — ritmo mais frequente?", "Fibrilação ventricular · 60–80% dos casos · sem RCP/desfibrilação tende a evoluir para assistolia"),
    card("FV — única forma de reversão definitiva?", "Desfibrilação elétrica · a cada minuto sem desfibrilação a chance de reversão cai cerca de 10%; após 10 min, é < 5%"),
    card("RCP de alta qualidade — profundidade e frequência?", "Compressões de 5–6 cm · frequência de 100–120/min"),
    card("RCP de alta qualidade — dois cuidados críticos?", "Permitir retorno completo do esterno · minimizar interrupções, idealmente < 10 s sem compressão"),
    card("BLS — sequência CAB?", "Circulation · compressões primeiro · Airway · abrir via aérea · Breathing · ventilações"),
    card("RCP por socorrista treinado — relação e ciclo?", "30 compressões : 2 ventilações · cinco séries correspondem a um ciclo de aproximadamente 2 min"),
    card("Após um choque em FV/TV sem pulso — checar pulso/ritmo?", "Não imediatamente · reiniciar RCP de pronto por 2 min · só então checar ritmo"),
    card("RCP com via aérea avançada — compressões e ventilações?", "Compressões contínuas 100–120/min · 1 ventilação a cada 6 s, total de 10/min"),
    card("ACLS — vasopressor indicado, dose e intervalo?", "Adrenalina 1 mg IV em bolus · repetir a cada 3–5 min durante a reanimação · quanto mais precoce, melhor"),
    card("Amiodarona na FV/TV refratária — doses?", "Primeira dose 300 mg IV em bolus · se persistir após novo choque, 150 mg IV · única droga que aumenta chance de retorno da circulação espontânea na FV/TV"),
    card("Se amiodarona indisponível na PCR — alternativa?", "Lidocaína · dose inicial 1–1,5 mg/kg · depois doses menores repetidas conforme protocolo"),
    card("Sequência organizacional adrenalina/amiodarona nos choques?", "Textos/AHA: adrenalina após 2º choque e amiodarona após 3º · na prática, epinefrina precoce e amiodarona em seguida"),
    card("PCR sem acesso venoso — adrenalina pelo tubo?", "Pode ser dada pelo tubo traqueal em dose 2–3 vezes maior que a IV · amiodarona não deve ser administrada pelo tubo"),
    card("Quais são os 5 H's da PCR?", "Hipóxia · Hipovolemia · H+ (acidose) · Hipo/Hipercalemia · Hipotermia"),
    card("Quais são os 5 T's da PCR?", "Trombose coronariana (IAM) · Trombose pulmonar (TEP) · Toxicidade · Tensão no tórax (PTx hipertensivo) · Tamponamento cardíaco"),
    card("Pista clínica dos 5 T's pela jugular?", "Turgência jugular sugere tamponamento, pneumotórax, TEP ou IAM · traqueia desviada reforça pneumotórax hipertensivo"),
    card("O que NÃO fazer de rotina na PCR?", "SF, sulfato de magnésio e bicarbonato de sódio de rotina · Mg 1–2 g IV só se suspeita de torsades · esteroides não são rotina"),
    card("Capnografia na via aérea avançada — papel?", "Confirma posição endotraqueal pelo CO₂ exalado · monitoração contínua detecta desposicionamento no transporte"),
    card("Cuidados pós-PCR com CDT?", "Controle direcionado da temperatura 32–36 °C por ≥ 24 h se permanece em coma · reduz mortalidade e melhora prognóstico neurológico · via aérea avançada torna-se necessária"),
    card("AESP — causas mais comuns citadas?", "Insuficiência respiratória com hipóxia e acidose respiratória · hipovolemia"),
    card("PCR por asfixia/hipóxia — particularidade inicial?", "Realizar primeiro um ciclo de 2 min de RCP antes de chamar ajuda, pois a hipóxia já está presente desde o início"),
    card("DEA — conduta após ele indicar/aplicar choque?", "Retomar compressões imediatamente · não checar pulso ou ritmo antes do próximo ciclo de RCP"),
    card("PCR intra-hospitalar — proporção de ritmos?", "FV em cerca de 1/3 · assistolia ou AESP nos 2/3 restantes, pela maior carga de doenças de base"),
  ]),
  deck("cardio-antiarrhythmicos", "Antiarrítmicos · Vaughan Williams", [
    card("Potencial de ação — fases 0, 2 e 3?", "Fase 0 · abertura de canais de sódio · fase 2 · cálcio · fase 3 · potássio"),
    card("Por que NSA/NAV diferem na fase 0?", "Fase 0 do nó sinusal e NAV depende de canais de cálcio, não de sódio"),
    card("Vaughan Williams — grupos IA, IB e IC?", "Todos bloqueiam sódio · IA: quinidina/procainamida/disopiramida · IB: lidocaína/fenitoína/mexiletina · IC: propafenona/flecainida"),
    card("Grupo IA — efeito no ECG e principal risco?", "Aumenta QRS em 10–20% e pode prolongar QT · torsades de pointes por pós-potenciais precoces, inclusive com quinidina"),
    card("Procainamida — aplicação-chave no Car3?", "Primeira escolha na FA com WPW e na TAVR antidrômica · bloqueia a via acessória"),
    card("Grupo IB — perfil da lidocaína?", "Bloqueia sódio com cinética rápida · atua em tecido isquêmico e em taquicardias rápidas · não aumenta QRS · lidocaína é apenas IV"),
    card("Lidocaína — efeitos adversos citados?", "Nistagmo · disartria · tremores · sonolência · confusão mental · convulsões"),
    card("Grupo IC — efeito e risco no pós-IAM?", "Maior aumento de QRS, ~25% · pode gerar condução lenta e pró-arritmia · CAST mostrou maior mortalidade ao suprimir ESV tardias pós-IAM"),
    card("Propafenona — efeitos adversos descritos?", "Bradiarritmias · broncoespasmo por efeito betabloqueador associado"),
    card("Grupo II — mecanismo e indicações antiarrítmicas?", "Betabloqueadores reduzem automatismo e atividade deflagrada adrenérgica · inibem NAV · úteis em arritmias dependentes de NAV, pós-IAM e tireotoxicose"),
    card("Grupo III — fármacos e mecanismo?", "Amiodarona · sotalol · ibutilida · bloqueiam potássio da repolarização, prolongam potencial de ação e PRE e podem bloquear reentrada"),
    card("Amiodarona × sotalol — torsades?", "Amiodarona aumenta QT, mas torsades é muito rara · sotalol associa-se a torsades, além do efeito betabloqueador"),
    card("Amiodarona — efeitos adversos crônicos centrais?", "Hipo/hipertireoidismo · hepatotoxicidade · fibrose pulmonar · microdepósitos corneanos · fotossensibilidade"),
    card("Amiodarona IV aguda — efeito adverso frequente?", "Hipotensão arterial em cerca de 25% dos pacientes"),
    card("Amiodarona — interações importantes?", "Eleva níveis de warfarin e alarga INR · eleva digoxina e pode precipitar intoxicação digitálica"),
    card("Ibutilida — papel e efeitos adversos?", "Muito eficaz para reversão de flutter e FA · pode causar cefaleia e torsades de pointes"),
    card("Grupo IV — drogas e efeitos?", "Verapamil e diltiazem · bloqueiam cálcio no nó sinusal/NAV · reduzem FC e resposta ventricular de FA/flutter · podem causar bradiarritmia e descompensar IC sistólica"),
    card("Adenosina — mecanismo e indicação principal?", "Bloqueia canais de cálcio e aumenta efeito vagal nos canais de potássio · droga de escolha em reentradas que usam NAV, como AVNRT e WPW ortodrômica"),
    card("Adenosina — dose prática?", "6 mg IV em 1–2 s · se não reverter, 12 mg IV"),
    card("Magnésio e digitálicos — papel antiarrítmico?", "Magnésio controla torsades · digitálicos, apesar de pró-arrítmicos, têm efeito vagotônico útil em arritmias dependentes do NAV"),
  ]),
  deck("cardio-bloqueios-ecg", "Bloqueios intraventriculares · extrassístoles", [
    card("BRD — critérios no ECG?", "R’ alargada em V1 · S alargada em D1 e V6 · no incompleto o padrão é semelhante, sem R’ e S muito alargadas"),
    card("BRE — critérios no ECG?", "S alargada em V1 · R alargada e ausência de Q em D1 e V6 · no incompleto, S e R menos alargadas"),
    card("BRD isolado × BRE no idoso — significado?", "BRD isolado não aumenta chance de cardiopatia nem piora prognóstico · BRE aos 60 anos associa-se a cardiopatia/disfunção de VE em cerca de 50%"),
    card("HBAE — critérios?", "Desvio importante do eixo para esquerda, -30º a -120º · após excluir necrose inferior · rS predominante em D2 e aVF"),
    card("HBPE — critérios?", "Eixo ~+120º · excluir necrose lateral alta e HVD · rS em D1/aVL e qR em aVR"),
    card("HBAE × HBPE — frequência e prognóstico?", "HBAE é bem mais comum e pode ocorrer em idosos sem cardiopatia · HBPE é raro e, no cardiopata, sugere maior comprometimento miocárdico"),
    card("Bloqueio bifascicular clássico?", "BRD + HBAE ou BRD + HBPE · pode evoluir para BAVT, sobretudo se novo na fase aguda do IAM"),
    card("Bloqueio trifascicular — exemplos?", "BRD + HBAE alternando com HBPE · BRD alternando com BRE · bloqueio bifascicular + BAV de 1º grau"),
    card("DCIV isolado × avançado — tratamento?", "Ramo/hemibloqueio isolado não necessita tratamento e não contraindica cronotrópicos negativos · bi/trifascicular tem risco de BAVT e pode exigir MP"),
    card("Como ler a nomenclatura do MP em 3–4 letras?", "1ª: câmara estimulada A/V/D · 2ª: câmara sentida · 3ª: resposta I/T/D · 4ª opcional: R = ajuste de frequência"),
    card("Extrassístole atrial — aspecto no ECG?", "Onda P precoce e de morfologia diferente da sinusal · QRS em geral normal · pode ter aberrância ou ser bloqueada sem QRS"),
    card("Extrassístole atrial bloqueada — diagnóstico diferencial?", "Pode simular BAV · há P precoce sem QRS porque ambos os ramos ainda estão refratários"),
    card("Extrassístole ventricular — aspecto e pausa?", "QRS aberrante precoce sem P extrassistólica · pausa pós-extrassistólica compensatória, com intervalo igual a dois ciclos sinusais"),
    card("Bigeminismo × trigeminismo × pares?", "Bigeminismo · uma ESV para cada batimento sinusal · trigeminismo · uma ESV a cada dois sinusais · duas ESV seguidas são pareadas"),
    card("ESV complexa — polimórfica, TVNS e R-sobre-T?", "Polimórfica · > 1 morfologia · ≥ 3 ESV seguidas = TV não sustentada · acoplamento curto no fim da T = R-sobre-T"),
    card("ESV — prognóstico e tratamento?", "Em cardiopatas, > 10/h ou formas complexas pioram prognóstico · não suprimir com antiarrítmico salvo sintomas; betabloqueador é escolha"),
    card("TVNS com cardiopatia estrutural — significado?", "Coronariopatia, CMD/CMH ou valvopatia + TVNS aumentam risco de morte súbita · pode indicar avaliação para CDI conforme contexto"),
    card("Ritmo idioventricular — critérios?", "QRS alargado de origem ventricular · FC < 40 bpm · ritmo de escape quando falham marcapassos superiores"),
  ]),
];

const out = path.join(__dirname, "..", "data", "flashcards-cardio.json");
const existing = fs.existsSync(out) ? JSON.parse(fs.readFileSync(out, "utf8")) : [];
const ids = new Set(newDecks.map(({ id }) => id));
const decks = [...existing.filter(({ id }) => !ids.has(id)), ...newDecks];

fs.writeFileSync(out, JSON.stringify(decks, null, 2) + "\n", "utf8");
const totalCards = newDecks.reduce((sum, { cards }) => sum + cards.length, 0);
console.log(`Car3: ${newDecks.map((d) => `${d.id} (${d.cards.length})`).join(" · ")}`);
console.log(`Total Car3: ${totalCards} cards`);
console.log(`Total no arquivo: ${decks.length} decks · ${decks.reduce((n, d) => n + d.cards.length, 0)} cards`);
